//Auto-generated by RSP Compiler
//Source: myView.rsp.html
part of app_deploy_to_cloud;

/** Template, myView, for rendering the view. */
Future myView(HttpConnect connect, {blogLink}) { //#2
  var _t0_, _cs_ = new List<HttpConnect>();
  HttpRequest request = connect.request;
  HttpResponse response = connect.response;
  if (!Rsp.init(connect, "text/html; charset=utf-8"))
    return new Future.value();

  response.write("""<!DOCTYPE html>
<html>
  <head>
    <title>Dart automatic deployment in the cloud</title>
  </head>
  <body>
    <h1>Dart automatic deployment in the cloud</h1>
    <h2>(GitHub, Drone, Heroku)</h2>
    <p>
      <a id="btn-to-blog" data-link=\""""); //#2

  response.write(Rsp.nnx(blogLink.link)); //#11


  response.write("""" href="#">See blog article</a>
    </p>
    
    <script type="application/dart" src="/client/myView.dart"></script>
    <script src="/packages/browser/dart.js"></script>    
  </body>
</html>
"""); //#11

  return new Future.value();
}
